### ISSUE TITLE
Deleted pages aren't automatically deleted from the deployed site

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/docs#1071]
Due to 3a2c4d61ae8aefea123a086efbc2bd8e990f21e7

**Comment by musalbas** [comment]
cc @MSevey

**Comment by MSevey** [comment]
@musalbas this was previously solved with the workflow with @jcstein 
The normal deploy doesn't delete anything on the gh pages branch so that we can use the preview. 
But for instances that we need to remove old pages, we just need to manually trigger the deploy and it will clear out any old data.

**Comment by jcstein** [comment]
I wonder if there is a way to trigger this "Deploy with GH Pages" when pages are removed?

**Comment by musalbas** [comment]
I don't think clearing out all pages manually is a sufficient solution, ideally the workflow should be fixed such that old pages aren't kept around

**Comment by MSevey** [comment]
The crux of the issue is that our current deploy action does not have a fine grained control of removing files from the deployed `gh-pages` branch. 

There are 3 options to work around this:

1. Changes to the preview action
2. Changes to the deploy action
3. Manual script

## Option 1: Changes to the Preview Action

The preview action has the option to deploy the previews to a different repository. 

### Pros

The benefit of this option is that it keeps previews completely separate from the main site. There would be an entirely separate repo for the previews and this repo could also be used as a testing ground for other doc changes.  

Since it is a separate repo it is also a completely separate website. This reduces overall bloat to the docs site in the long run and avoids any issues with previews and deploys conflicting. 

### Cons

Yet another repo.

## Option 2: Changes to the Deploy Action

This option would involve moving from our current deploy action to the action that the pr-preview uses under the hood which does have fine grained control of what files to keep vs delete. 

### Pros

Minimal changes in total.

### Cons

Previews and deploys are still all on the same branch. Deploys currently work quite well, would be changing a core action vs changing a feature of an existing action.

## Option 3: Manual Script

We could add a manual clean up script that purges files on the gh-pages branch. There is potentially an action that already does this but would need to investigate. 

## Pros

Don't need to change actions and have more fine grained control over what files are on the branch.

## Cons

More code to maintain, implementing something that is essentially solved in other places already. 


cc @jcstein

**Comment by MSevey** [comment]
For context:
* I tested an MVP of option 1 already
* the pr preview action references the deploy action that has more control of what files to not delete
* option 3 is just an idea, no testing and research done yet but we have existing code that adds and commits changes to branches already.

**Comment by musalbas** [comment]
I don't think it makes sense for PR previews to be hosted on the production domain (docs.celestia.org) anyways

**Comment by jcstein** [comment]
does [this PR](https://github.com/celestiaorg/docs/pull/1074) resolve this issue?

**Comment by musalbas** [comment]
I don't think so. AFAIK this removes the commit history of gh-pages, but deleted files are still there.

**Comment by jcstein** [comment]
Hi @MSevey thank you for the help here.

When I initially read Option 1, I thought it meant maintaining two repositories of the actual documentation. Can you confirm if my understanding correct for Option 1, that the docs repo would exist as-is, and that only for the PR previews, they would be pushed to a separate repository? i.e. Similarly to how the gh-pages branch works now?

If that is the case, I think Option 1 is the cleanest. If the second repo is just used to publish PR previews, it makes sense to me. However, if it means making changes in the PR preview repo, then having to make a PR from main of that repo to the main docs repo, to update the site, I don't think this is really a smooth path forward.

**Comment by MSevey** [comment]
> Hi @MSevey thank you for the help here.
> 
> 
> 
> When I initially read Option 1, I thought it meant maintaining two repositories of the actual documentation. Can you confirm if my understanding correct for Option 1, that the docs repo would exist as-is, and that only for the PR previews, they would be pushed to a separate repository? i.e. Similarly to how the gh-pages branch works now?
> 
> 
> 
> If that is the case, I think Option 1 is the cleanest. If the second repo is just used to publish PR previews, it makes sense to me. However, if it means making changes in the PR preview repo, then having to make a PR from main of that repo to the main docs repo, to update the site, I don't think this is really a smooth path forward.

@jcstein Yes for option 1 the second repo should be totally automated by GitHub actions. I'll need to revisit the demo I did to confirm this but it wouldn't require PRs in both.
