### ISSUE TITLE
Ideas for full-consensus-node page

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#1640]
While working on a separate issue, I observed a few things on: https://docs.celestia.org/nodes/full-consensus-node. Ideas for improvement:

- Update title to: Full consensus node 
- "hardware minimum requirements" -> "minimum hardware requirements"
- "If you are not using pruning, you are running an archive node, and it is recommended to have 500 GB of SSD storage. Please ensure that your storage meets this requirement to ensure smooth syncing and operation of the node." I think this line needs to be updated because I ran a node that synced from genesis without pruning and needed 1300 GB.
- "Setting up a full consensus node" -> Set up a consensus full node
- We should be consistent about usage of "full consensus node" vs. "consensus full node"
- Subheadings don't need "-ing"
- I don't think we need to clone the networks repo anymore because the `download-genesis` command
- Explain what persistent peers do
- Explain (or link) to a sentry node
- "Connecting a consensus node to a bridge node" section should be marked optional
- "Accessing historical state" section should be marked optional.
- https://docs.celestia.org/nodes/full-consensus-node#syncing we should provide time estimates for each of these three options. Block sync will take several weeks. Block sync should also state something like: "from genesis up to the tip"
- "Refer to [the ports section of the celestia-node troubleshooting page](https://docs.celestia.org/nodes/celestia-node-troubleshooting#ports) for information on which ports are required to be open on your machine." Why do we need a link to celestia-node ports section here? Can we remove this tip?

**Comment by jcstein** [comment]
Related to #1661 and #1650

**Comment by jcstein** [comment]
- [ ] Update title to: Full consensus node
- [ ] "hardware minimum requirements" -> "minimum hardware requirements"
- [ ] "If you are not using pruning, you are running an archive node, and it is recommended to have 500 GB of SSD storage. Please ensure that your storage meets this requirement to ensure smooth syncing and operation of the node." I think this line needs to be updated because I ran a node that synced from genesis without pruning and needed 1300 GB.
- [ ] "Setting up a full consensus node" -> Set up a consensus full node
- [ ] We should be consistent about usage of "full consensus node" vs. "consensus full node"
- [ ] Subheadings don't need "-ing"
- [ ] I don't think we need to clone the networks repo anymore because the download-genesis command
- [ ] Explain what persistent peers do
- [ ] Explain (or link) to a sentry node
- [ ] "Connecting a consensus node to a bridge node" section should be marked optional
- [ ] "Accessing historical state" section should be marked optional.
- [ ] https://docs.celestia.org/nodes/full-consensus-node#syncing we should provide time estimates for each of these three options. Block sync will take several weeks. Block sync should also state something like: "from genesis up to the tip"
- [ ] "Refer to [the ports section of the celestia-node troubleshooting page](https://docs.celestia.org/nodes/celestia-node-troubleshooting#ports) for information on which ports are required to be open on your machine." Why do we need a link to celestia-node ports section here? Can we remove this tip?
