### ISSUE TITLE
All internal links should have trailing slash

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/docs#425]
For consistency, all internal links to docs.celestia.org should have a trailing slash as that is the canonical URL as that is what the web server will redirect you to if you load a URL without a trailing slash.

**Comment by Gunter038** [comment]
Hello @musalbas. It seems risky : https://docusaurus.io/docs/markdown-features/links

Docusaurus is built around files. 

Using relative file paths (with .md extensions) instead of relative URL links provides the following benefits:

- Links will keep working on the GitHub interface and many Markdown editors
- You can customize the files' slugs without having to update all the links
- Moving files around the folders can be tracked by your editor, and some editors may automatically update file links
- A [versioned doc](https://docusaurus.io/docs/versioning) will link to another doc of the exact same version
- Relative URL links are very likely to break if you update the [trailingSlash config](https://docusaurus.io/docs/api/docusaurus-config#trailingSlash)

I think that it's important to keep that in mind before changing anything.

**Comment by musalbas** [comment]
I'm just saying that hrefs in the compiled html should have a `/` at the end of it, so for example instead of linking to https://docs.celestia.org/developers/ethermint, we should link to https://docs.celestia.org/developers/ethermint/. This shouldn't need to change the actual folder structure or anything like that, ideally. Btw `trailingSlash` is enabled by default according to the docs.

**Comment by jcstein** [comment]
Will review and fix this @musalbas, thank you for submitting issue
