### ISSUE TITLE
Docker section does not handle persistent volumes

### ISSUE THREAD

**Issue by smuu** [celestiaorg/docs#508]
https://docs.celestia.org/nodes/docker-images/

This section does not explain handling volumes to have persistent data when restarting the container.

Also: Currently, our container runs with the root user, which will be changed in the future. So, the volume you mount needs to have the correct permission. Ref.: https://github.com/celestiaorg/celestia-app/pull/1473#discussion_r1133758393

I am happy to help with technical details.

**Comment by smuu** [comment]
It would also be great to put that to the `celestia-app` and `celestia-node` README.

**Comment by jcstein** [comment]
I think it may be best if we pair on this to start next week and then hopefully I can implement best guidance. How does that sound?

I'm not sure if it makes sense to add to the instructions to readmes because then updates will require them to be updated too, but I could be wrong here. Will plan to add guidance for using `celestia-app` currently on our docs, as it doesn't exist yet
